# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Login(object):
    def setupUi(self, Login):
        Login.setObjectName("Login")
        Login.resize(548, 388)
        self.File_import_2 = QtWidgets.QLabel(Login)
        self.File_import_2.setGeometry(QtCore.QRect(70, 30, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(16)
        self.File_import_2.setFont(font)
        self.File_import_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.File_import_2.setMidLineWidth(0)
        self.File_import_2.setObjectName("File_import_2")
        self.widget = QtWidgets.QWidget(Login)
        self.widget.setGeometry(QtCore.QRect(100, 110, 51, 111))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.widget_2 = QtWidgets.QWidget(Login)
        self.widget_2.setGeometry(QtCore.QRect(180, 100, 231, 141))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.id = QtWidgets.QLineEdit(self.widget_2)
        self.id.setObjectName("id")
        self.verticalLayout_2.addWidget(self.id)
        self.pwd = QtWidgets.QLineEdit(self.widget_2)
        self.pwd.setObjectName("pwd")
        self.verticalLayout_2.addWidget(self.pwd)
        self.widget_3 = QtWidgets.QWidget(Login)
        self.widget_3.setGeometry(QtCore.QRect(100, 260, 301, 61))
        self.widget_3.setObjectName("widget_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_3)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.login = QtWidgets.QPushButton(self.widget_3)
        self.login.setObjectName("login")
        self.horizontalLayout.addWidget(self.login)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.regiest = QtWidgets.QPushButton(self.widget_3)
        self.regiest.setObjectName("regiest")
        self.horizontalLayout.addWidget(self.regiest)

        self.retranslateUi(Login)
        QtCore.QMetaObject.connectSlotsByName(Login)

    def retranslateUi(self, Login):
        _translate = QtCore.QCoreApplication.translate
        Login.setWindowTitle(_translate("Login", "Form"))
        self.File_import_2.setText(_translate("Login", "<html><head/><body><p><span style=\" font-size:10pt;\">基于深度学习+OpenCV的车载行人障碍物检测系统设计与实现</span></p></body></html>"))
        self.label_2.setText(_translate("Login", "密码"))
        self.label.setText(_translate("Login", "账号"))
        self.login.setText(_translate("Login", "登录"))
        self.regiest.setText(_translate("Login", "注册"))
