# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regiest.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Regiest(object):
    def setupUi(self, Regiest):
        Regiest.setObjectName("Regiest")
        Regiest.resize(466, 356)
        self.File_import_2 = QtWidgets.QLabel(Regiest)
        self.File_import_2.setGeometry(QtCore.QRect(40, 20, 401, 21))
        font = QtGui.QFont()
        font.setFamily("Adobe 宋体 Std L")
        font.setPointSize(16)
        self.File_import_2.setFont(font)
        self.File_import_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.File_import_2.setMidLineWidth(0)
        self.File_import_2.setObjectName("File_import_2")
        self.widget = QtWidgets.QWidget(Regiest)
        self.widget.setGeometry(QtCore.QRect(60, 60, 91, 161))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.id = QtWidgets.QLineEdit(Regiest)
        self.id.setGeometry(QtCore.QRect(160, 70, 131, 31))
        self.id.setObjectName("id")
        self.code_display = QtWidgets.QLabel(Regiest)
        self.code_display.setGeometry(QtCore.QRect(240, 190, 91, 51))
        self.code_display.setText("")
        self.code_display.setObjectName("code_display")
        self.pwd = QtWidgets.QLineEdit(Regiest)
        self.pwd.setGeometry(QtCore.QRect(160, 150, 131, 31))
        self.pwd.setObjectName("pwd")
        self.code_input = QtWidgets.QLineEdit(Regiest)
        self.code_input.setGeometry(QtCore.QRect(160, 200, 71, 31))
        self.code_input.setObjectName("code_input")
        self.regiest_check = QtWidgets.QPushButton(Regiest)
        self.regiest_check.setGeometry(QtCore.QRect(90, 270, 81, 31))
        self.regiest_check.setObjectName("regiest_check")
        self.return_push = QtWidgets.QPushButton(Regiest)
        self.return_push.setGeometry(QtCore.QRect(254, 270, 81, 31))
        self.return_push.setObjectName("return_push")
        self.reflush = QtWidgets.QPushButton(Regiest)
        self.reflush.setGeometry(QtCore.QRect(350, 200, 81, 31))
        self.reflush.setObjectName("reflush")
        self.repwd = QtWidgets.QLineEdit(Regiest)
        self.repwd.setGeometry(QtCore.QRect(160, 110, 131, 31))
        self.repwd.setObjectName("repwd")
        self.log = QtWidgets.QLabel(Regiest)
        self.log.setGeometry(QtCore.QRect(310, 70, 121, 41))
        self.log.setText("")
        self.log.setObjectName("log")

        self.retranslateUi(Regiest)
        QtCore.QMetaObject.connectSlotsByName(Regiest)
        Regiest.setTabOrder(self.id, self.repwd)
        Regiest.setTabOrder(self.repwd, self.pwd)
        Regiest.setTabOrder(self.pwd, self.code_input)
        Regiest.setTabOrder(self.code_input, self.reflush)
        Regiest.setTabOrder(self.reflush, self.regiest_check)
        Regiest.setTabOrder(self.regiest_check, self.return_push)

    def retranslateUi(self, Regiest):
        _translate = QtCore.QCoreApplication.translate
        Regiest.setWindowTitle(_translate("Regiest", "Form"))
        self.File_import_2.setText(_translate("Regiest", "<html><head/><body><p><span style=\" font-size:10pt;\">基于深度学习+OpenCV的车载行人障碍物检测系统设计与实现</span></p></body></html>"))
        self.label_2.setText(_translate("Regiest", "    账号"))
        self.label.setText(_translate("Regiest", "    密码"))
        self.label_4.setText(_translate("Regiest", "再次输入密码"))
        self.label_3.setText(_translate("Regiest", "   验证码"))
        self.regiest_check.setText(_translate("Regiest", "注册"))
        self.return_push.setText(_translate("Regiest", "返回"))
        self.reflush.setText(_translate("Regiest", "刷新验证码"))
